I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 10, in script
    define flashbulb = fade(0.2, 0.0, 0.8, color='#fff')
  File "game/script.rpy", line 10, in script
    define flashbulb = fade(0.2, 0.0, 0.8, color='#fff')
  File "game/script.rpy", line 10, in <module>
    define flashbulb = fade(0.2, 0.0, 0.8, color='#fff')
TypeError: Fade() got multiple values for argument 'color'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\RenPy\renpy-7.4.11-sdk\renpy\bootstrap.py", line 274, in bootstrap
    renpy.main.main()
  File "D:\RenPy\renpy-7.4.11-sdk\renpy\main.py", line 558, in main
    renpy.game.context().run(node)
  File "game/script.rpy", line 10, in script
    define flashbulb = fade(0.2, 0.0, 0.8, color='#fff')
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "game/script.rpy", line 10, in script
    define flashbulb = fade(0.2, 0.0, 0.8, color='#fff')
  File "D:\RenPy\renpy-7.4.11-sdk\renpy\ast.py", line 2441, in execute
    self.set()
  File "D:\RenPy\renpy-7.4.11-sdk\renpy\ast.py", line 2455, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "D:\RenPy\renpy-7.4.11-sdk\renpy\python.py", line 1073, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 10, in <module>
    define flashbulb = fade(0.2, 0.0, 0.8, color='#fff')
TypeError: Fade() got multiple values for argument 'color'

Windows-10-10.0.19043 AMD64
Ren'Py 8.0.1.22070801
The Cave 0.1
Wed Aug 10 23:25:42 2022
