I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 142, in script
    if pockets:
  File "game/script.rpy", line 142, in <module>
    if pockets:
NameError: name 'pockets' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 142, in script
    if pockets:
  File "D:\RenPy\renpy-7.4.11-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "D:\RenPy\renpy-7.4.11-sdk\renpy\python.py", line 1080, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\RenPy\renpy-7.4.11-sdk\renpy\python.py", line 1073, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 142, in <module>
    if pockets:
NameError: name 'pockets' is not defined

Windows-10-10.0.19043 AMD64
Ren'Py 8.0.1.22070801
The Cave 0.1.1.1
Sun Aug 14 21:12:52 2022
